trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m unittest discover -s ./tests -p 'main.py'
  displayName: 'Run tests'